[build]
builder = "dockerfile"

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:8080 --workers 1 --timeout 600 --worker-class sync"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
