"""
Export packager.

Collects all generated files and produces a platform-ready zip archive
with README, platform specs, and ready-to-upload deliverables.

Output structure inside the zip
────────────────────────────────
<artist>_<album>/
├── README.txt                       <- spec sheet and upload instructions
├── album_cover.png                  <- 3000x3000 @ 300 DPI (print-ready)
├── spotify/
│   └── canvas.mp4                   <- 720x1280, H.264, 8s loop
└── youtube/
    └── visualizer.mp4               <- 1920x1080, H.264 + AAC
"""

from __future__ import annotations

import zipfile
from pathlib import Path


PLATFORM_SPECS = """\
ARTWORK MACHINE -- EXPORT PACKAGE
==================================

ALBUM COVER
  Format : PNG, RGB, 3000x3000 px
  DPI    : 300 (print-ready)
  Usage  : Album cover, merchandise, digital stores (Spotify, Apple Music, etc.)

SPOTIFY CANVAS
  Format   : MP4 (H.264)
  Size     : 720x1280 (9:16 portrait)
  Duration : 8 seconds (seamless loop)
  Upload   : Spotify for Artists -> Song -> Canvas

YOUTUBE VISUALIZER
  Format   : MP4 (H.264 + AAC 320k)
  Size     : 1920x1080 (16:9 landscape)
  Duration : Full track length
  Upload   : YouTube Studio -> Upload Video

Generated by artwork-machine
"""


def package(
    album_cover: Path,
    canvas: Path,
    visualizer: Path,
    output_zip: Path,
    artist: str,
    album: str,
) -> Path:
    """
    Zip all deliverables into a single archive.

    Parameters
    ----------
    output_zip:
        Destination path for the .zip file.
    """
    output_zip.parent.mkdir(parents=True, exist_ok=True)
    slug = f"{_slug(artist)}_{_slug(album)}"

    with zipfile.ZipFile(str(output_zip), "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{slug}/README.txt", PLATFORM_SPECS)

        if album_cover.exists():
            zf.write(str(album_cover), f"{slug}/album_cover.png")
        if canvas.exists():
            zf.write(str(canvas), f"{slug}/spotify/canvas.mp4")
        if visualizer.exists():
            zf.write(str(visualizer), f"{slug}/youtube/visualizer.mp4")

    return output_zip


def _slug(text: str) -> str:
    import re
    return re.sub(r"[^a-zA-Z0-9]", "_", text)[:40]
