"""
Export packager.

Collects all generated files and produces a platform-ready zip archive
with README, platform specs, and ready-to-upload deliverables.

Output structure inside the zip
────────────────────────────────
<artist>_<album>/
├── README.txt                       ← spec sheet and upload instructions
├── cassette/
│   ├── cassette_side_A.png          ← 3000×3000 @ 300 DPI (print-ready)
│   └── cassette_side_B.png
├── spotify/
│   └── canvas.mp4                   ← 720×1280, H.264, 8 s loop
└── youtube/
    └── visualizer.mp4               ← 1920×1080, H.264 + AAC
"""

from __future__ import annotations

import zipfile
from pathlib import Path


PLATFORM_SPECS = """\
ARTWORK MACHINE — EXPORT PACKAGE
=================================

CASSETTE ARTWORK
  Format : PNG, RGBA, 3000×3000 px
  DPI    : 300 (print-ready)
  Usage  : Album cover, merchandise, digital stores

SPOTIFY CANVAS
  Format   : MP4 (H.264, AAC)
  Size     : 720×1280 (9:16 portrait)
  Duration : 8 seconds (seamless loop)
  Upload   : Spotify for Artists → Song → Canvas

YOUTUBE VISUALIZER
  Format   : MP4 (H.264 + AAC)
  Size     : 1920×1080 (16:9 landscape)
  Duration : Full track length
  Upload   : YouTube Studio → Upload Video
             Set as "Visualizer" in title/description

Generated by artwork-machine (github.com/your-org/artwork-machine)
"""


def package(
    cassette_a: Path,
    cassette_b: Path,
    canvas: Path,
    visualizer: Path,
    output_zip: Path,
    artist: str,
    album: str,
) -> Path:
    """
    Zip all deliverables into a single archive.

    Parameters
    ----------
    output_zip:
        Destination path for the .zip file.
    """
    output_zip.parent.mkdir(parents=True, exist_ok=True)
    slug = f"{_slug(artist)}_{_slug(album)}"

    with zipfile.ZipFile(str(output_zip), "w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(f"{slug}/README.txt", PLATFORM_SPECS)

        if cassette_a.exists():
            zf.write(str(cassette_a), f"{slug}/cassette/cassette_side_A.png")
        if cassette_b.exists():
            zf.write(str(cassette_b), f"{slug}/cassette/cassette_side_B.png")
        if canvas.exists():
            zf.write(str(canvas), f"{slug}/spotify/canvas.mp4")
        if visualizer.exists():
            zf.write(str(visualizer), f"{slug}/youtube/visualizer.mp4")

    return output_zip


def _slug(text: str) -> str:
    import re
    return re.sub(r"[^a-zA-Z0-9]", "_", text)[:40]
